#!/bin/bash
# ═══════════════════════════════════════════════════════════
# ASIMOV-AI: Auto-create NotebookLM Governance Notebook
# Generated by ASIMOV-AI Configuration Wizard (Antigravity)
# ═══════════════════════════════════════════════════════════
# Usage: bash ~/Downloads/asimov_nlm_setup.sh
# Requires: nlm CLI authenticated — run `nlm login` first
# ═══════════════════════════════════════════════════════════

set -e

# ── Edit these to match your wizard output ─────────────────
SECTOR="Your Sector (SRA regulated)"
COMM_TOOL="Microsoft Teams"
DOC_TOOL="SharePoint"
HITL_TOOL="Microsoft Lists"
AI_TOOLS="Claude, Gemini / NotebookLM"
COMPLIANCE="EU AI Act (high-risk), GDPR, SRA Principles (UK legal)"
TEAM_SIZE="11-50 people"
# ───────────────────────────────────────────────────────────

NOTEBOOK_TITLE="ASIMOV — ${SECTOR} Governance Notebook"

echo ""
echo "════════════════════════════════════════════════════════"
echo " ASIMOV-AI NotebookLM Governance Notebook Setup"
echo "════════════════════════════════════════════════════════"
echo " Sector   : $SECTOR"
echo " Comm tool : $COMM_TOOL"
echo " Doc store : $DOC_TOOL"
echo " HITL tool : $HITL_TOOL"
echo " AI tools  : $AI_TOOLS"
echo "════════════════════════════════════════════════════════"
echo ""

# Step 1: Create notebook
echo "▸ Creating notebook: $NOTEBOOK_TITLE"
NB_ID=$(nlm notebook create "$NOTEBOOK_TITLE" --quiet)
echo "  ✓ Notebook ID: $NB_ID"
nlm alias set asimov-governance "$NB_ID" 2>/dev/null || true

# Step 2: Add YAML config as source
echo ""
echo "▸ Adding ASIMOV YAML config as source..."
YAML_CONTENT="# Cowork Skill: Collaboration Environment Setup
# Generated by ASIMOV-AI Configuration Wizard
# Sector: ${SECTOR}
# BMAD Standards + 4-Eyes Protocol enforced

skill:
  name: setup_collaboration_environment
  description: >
    Provisions a governed collaboration environment for
    ${SECTOR} teams using available tooling.
  platforms: [Mac, Windows, iOS, Android, iPad]
  ai_tools: [${AI_TOOLS}]
  governance: BMAD + 4-Eyes Protocol

steps:
  - step: 1_communication
    tool: ${COMM_TOOL}
    actions:
      - Create matter/project channels (one per active engagement)
      - Create #ai-outputs channel (all AI-generated content posted here pre-review)
      - Create #governance channel (compliance notifications)
      - Assign channel owners with named HITL roles

  - step: 2_documents
    tool: ${DOC_TOOL}
    actions:
      - Create standard folder structure:
          /Active Matters
          /AI Outputs (pending review)
          /AI Outputs (approved)
          /Governance
          /Templates
          /Audit Logs

  - step: 3_hitl_register
    tool: ${HITL_TOOL}
    actions:
      - Create HITL Register with columns:
          Task Type | AI Tool Used | HITL Reviewer | Sign-off Date | Matter Ref
      - Link register to #ai-outputs channel
      - 4-Eyes gate: no AI output reaches client without register entry

  - step: 4_compliance_frame
    requirements:
      - Compliance: ${COMPLIANCE}
      - Data residency: confirm all tools set to UK/EU region

  - step: 5_ai_integration
    tools: [${AI_TOOLS}]
    actions:
      - AI generates draft -> posted to #ai-outputs
      - Named HITL reviewer signs off (4-Eyes gate)
      - Approved output moves to document library
      - HITL Register updated automatically
      - Audit log entry created
      - Schedule 90-day governance review checkpoint

# Team size: ${TEAM_SIZE}"

nlm source add "$NB_ID" --text "$YAML_CONTENT" --title "ASIMOV Config — ${SECTOR}"
echo "  ✓ YAML config added"

# Step 3: Add HITL protocol context
echo ""
echo "▸ Adding HITL protocol & compliance context..."
HITL_TEXT="4-Eyes Protocol: All AI outputs must be logged in the HITL Register (${HITL_TOOL}) before client delivery. No exceptions. Compliance requirements: ${COMPLIANCE}. AI tools in scope: ${AI_TOOLS}. Communication platform: ${COMM_TOOL}. Document storage: ${DOC_TOOL}. Team size: ${TEAM_SIZE}. BMAD workflow stages: Analyst (research & index) -> Architect (legal logic) -> Drafting (output generation) -> 4-Eyes Review (HITL sign-off) -> Monitoring (audit trail)."
nlm source add "$NB_ID" --text "$HITL_TEXT" --title "HITL Protocol & Compliance Framework"
echo "  ✓ HITL context added"

# Step 4: Generate governance briefing doc
echo ""
echo "▸ Generating governance briefing report (this takes ~30s)..."
nlm report create "$NB_ID" --format "Briefing Doc" --confirm
echo "  ✓ Briefing Doc queued"

# Step 5: Generate team onboarding study guide
echo ""
echo "▸ Generating team onboarding study guide..."
nlm report create "$NB_ID" --format "Study Guide" --confirm
echo "  ✓ Study Guide queued"

# Done
echo ""
echo "════════════════════════════════════════════════════════"
echo " ✓ ASIMOV Governance Notebook created!"
echo ""
echo "  Notebook : $NOTEBOOK_TITLE"
echo "  ID       : $NB_ID"
echo "  Alias    : asimov-governance"
echo ""
echo " Next steps:"
echo "  nlm studio status asimov-governance   # Check report progress"
echo "  nlm notebook query asimov-governance \"What are the HITL requirements?\""
echo "  nlm download report asimov-governance --output asimov_briefing.md"
echo "════════════════════════════════════════════════════════"
echo ""
