import React, { useState } from 'react';

export default function ASIMOVConfigWizard() {
  const [step, setStep] = useState(1);
  const [config, setConfig] = useState({
    sector: '',
    teamSize: '',
    commTool: '',
    docTool: '',
    hitlTool: '',
    aiTools: [],
    complianceReqs: []
  });
  const [generatedYAML, setGeneratedYAML] = useState('');
  const [generatedScript, setGeneratedScript] = useState('');

  const questions = [
    {
      id: 'sector',
      question: 'What sector is this deployment for?',
      type: 'select',
      options: [
        'Law firm (SRA regulated)',
        'Accountancy practice (ICAEW/ACCA regulated)',
        'Architecture firm (ARB regulated)',
        'Financial services (FCA regulated)',
        'Healthcare practice (CQC regulated)',
        'Other professional services'
      ]
    },
    {
      id: 'teamSize',
      question: 'What is the team size?',
      type: 'select',
      options: ['1-10 people', '11-50 people', '51-200 people', '200+ people']
    },
    {
      id: 'commTool',
      question: 'Which communication platform?',
      type: 'select',
      options: ['Microsoft Teams', 'Slack', 'Google Chat', 'Other']
    },
    {
      id: 'docTool',
      question: 'Which document storage platform?',
      type: 'select',
      options: ['Google Drive', 'SharePoint', 'Dropbox', 'OneDrive', 'Other']
    },
    {
      id: 'hitlTool',
      question: 'Which tool for the HITL Register?',
      type: 'select',
      options: ['Microsoft Lists', 'Google Sheets', 'Airtable', 'Excel Online', 'Other']
    },
    {
      id: 'aiTools',
      question: 'Which AI tools will be used? (Select all that apply)',
      type: 'multiselect',
      options: ['Claude', 'ChatGPT', 'Harvey', 'Gemini / NotebookLM', 'GitHub Copilot', 'Other']
    },
    {
      id: 'complianceReqs',
      question: 'Which compliance requirements apply? (Select all that apply)',
      type: 'multiselect',
      options: [
        'EU AI Act (high-risk)',
        'GDPR',
        'SRA Principles (UK legal)',
        'FCA regulations',
        'HIPAA (healthcare)',
        'ISO 27001',
        'AML/KYC requirements',
        'Other'
      ]
    }
  ];

  const currentQuestion = questions[step - 1];

  const handleAnswer = (value) => {
    if (currentQuestion.type === 'multiselect') {
      const current = config[currentQuestion.id] || [];
      const updated = current.includes(value)
        ? current.filter(v => v !== value)
        : [...current, value];
      setConfig({ ...config, [currentQuestion.id]: updated });
    } else {
      setConfig({ ...config, [currentQuestion.id]: value });
    }
  };

  const canProceed = () => {
    const answer = config[currentQuestion.id];
    if (currentQuestion.type === 'multiselect') {
      return answer && answer.length > 0;
    }
    return answer && answer.length > 0;
  };

  const generateYAML = () => {
    const channels = [];
    
    if (config.sector.includes('Law firm')) {
      channels.push('#sra-compliance channel');
    } else if (config.sector.includes('Accountancy')) {
      channels.push('#icaew-compliance channel');
    } else if (config.sector.includes('Architecture')) {
      channels.push('#arb-compliance channel');
    } else if (config.sector.includes('Financial')) {
      channels.push('#fca-compliance channel');
    }

    const complianceFrame = [];
    config.complianceReqs.forEach(req => {
      if (req.includes('SRA')) {
        complianceFrame.push('- SRA Principle 6 (client confidentiality): enforced via channel permissions');
      }
      if (req.includes('EU AI Act')) {
        complianceFrame.push('- EU AI Act (Aug 2 2026 deadline): HITL register satisfies human oversight requirement');
      }
      if (req.includes('GDPR')) {
        complianceFrame.push('- GDPR: document storage must remain UK/EU hosted');
      }
      if (req.includes('FCA')) {
        complianceFrame.push('- FCA regulations: maintain audit trail of all AI-assisted decisions');
      }
      if (req.includes('HIPAA')) {
        complianceFrame.push('- HIPAA: ensure all AI tools are BAA-compliant');
      }
      if (req.includes('ISO 27001')) {
        complianceFrame.push('- ISO 27001: information security controls embedded in workflow');
      }
      if (req.includes('AML/KYC')) {
        complianceFrame.push('- AML/KYC: matter channels must log client verification status');
      }
    });

    const yaml = `# Cowork Skill: Collaboration Environment Setup
# Generated by ASIMOV-AI Configuration Wizard
# Sector: ${config.sector}
# ─────────────────────────────────────────────

skill:
  name: setup_collaboration_environment
  description: >
    Provisions a governed collaboration environment for
    ${config.sector} teams using available tooling.
  platforms: [Mac, Windows, iOS phone, Android phone, iPad / tablet]
  ai_tools: [${config.aiTools.join(', ')}]

steps:

  - step: 1_communication
    tool: ${config.commTool}
    actions:
      - Create matter/project channels (one per active engagement)
      - Create #general channel
      - Create #ai-outputs channel (all AI-generated content posted here pre-review)
      - Create #governance channel (compliance notifications)
      ${channels.length > 0 ? `- Create ${channels.join('\n      - Create ')}` : ''}
      - Assign channel owners with named HITL roles

  - step: 2_documents
    tool: ${config.docTool}
    actions:
      - Create standard folder structure:
          /Active Matters
          /AI Outputs (pending review)
          /AI Outputs (approved)
          /Governance
          /Templates
          /Audit Logs
      - Apply version control policy to all document libraries
      - Set role-based permissions (Partner / Associate / Admin)

  - step: 3_hitl_register
    tool: ${config.hitlTool}
    actions:
      - Create HITL Register with columns:
          Task Type | AI Tool Used | HITL Reviewer | Sign-off Date | Matter Ref
      - Link register to #ai-outputs channel
      - Set weekly reminder for HITL review sweep
      - Configure monthly export for ${config.sector.includes('SRA') ? 'SRA' : 'regulatory'} audit file

  - step: 4_compliance_frame
    requirements:
      ${complianceFrame.join('\n      ')}
      - Data residency: confirm all tools set to UK region

  - step: 5_ai_integration
    tools: [${config.aiTools.join(', ')}]
    actions:
      - Configure AI output workflow:
          1. AI generates draft
          2. Output posted to #ai-outputs channel
          3. Named HITL reviewer signs off
          4. Approved output moves to document library
          5. HITL Register updated automatically
      - Brief all users on Kill List and citation standards
      - Set 90-day review checkpoint

# ─────────────────────────────────────────────
# Next: run this skill via Cowork or pass to
# Claude Code for Microsoft Graph API automation
`;

    setGeneratedYAML(yaml);
  };

  const generateMicrosoftGraphScript = () => {
    const script = `"""
ASIMOV-AI Environment Provisioning Script
Generated for: ${config.sector}
Tools: ${config.commTool}, ${config.docTool}, ${config.hitlTool}

This script uses Microsoft Graph API to provision:
- Teams channels
- SharePoint folders
- Microsoft Lists (HITL Register)
"""

import requests
import json
from datetime import datetime

# ═══════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════

TENANT_ID = "your-tenant-id"
CLIENT_ID = "your-client-id"
CLIENT_SECRET = "your-client-secret"
TEAM_NAME = "${config.sector} - ASIMOV Workspace"

# Required Graph API permissions:
# - Group.ReadWrite.All
# - Sites.ReadWrite.All
# - TeamSettings.ReadWrite.All

# ═══════════════════════════════════════════════════════════
# AUTHENTICATION
# ═══════════════════════════════════════════════════════════

def get_access_token():
    url = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    data = {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "scope": "https://graph.microsoft.com/.default",
        "grant_type": "client_credentials"
    }
    response = requests.post(url, headers=headers, data=data)
    return response.json()["access_token"]

# ═══════════════════════════════════════════════════════════
# STEP 1: CREATE TEAM
# ═══════════════════════════════════════════════════════════

def create_team(token):
    url = "https://graph.microsoft.com/v1.0/teams"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }
    data = {
        "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
        "displayName": TEAM_NAME,
        "description": "ASIMOV-AI governed workspace for ${config.sector}"
    }
    response = requests.post(url, headers=headers, json=data)
    team_id = response.headers.get("Content-Location").split("'")[1]
    print(f"✓ Team created: {team_id}")
    return team_id

# ═══════════════════════════════════════════════════════════
# STEP 2: CREATE CHANNELS
# ═══════════════════════════════════════════════════════════

def create_channels(token, team_id):
    channels = [
        {"displayName": "ai-outputs", "description": "All AI-generated content posted here pre-review"},
        {"displayName": "governance", "description": "Compliance notifications and policy updates"},
        ${config.sector.includes('Law') ? '{"displayName": "sra-compliance", "description": "SRA regulatory tracking"},' : ''}
        {"displayName": "active-matters", "description": "Project and matter-specific discussions"}
    ]
    
    for channel in channels:
        url = f"https://graph.microsoft.com/v1.0/teams/{team_id}/channels"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        response = requests.post(url, headers=headers, json=channel)
        print(f"✓ Channel created: {channel['displayName']}")

# ═══════════════════════════════════════════════════════════
# STEP 3: CREATE SHAREPOINT FOLDERS
# ═══════════════════════════════════════════════════════════

def create_sharepoint_folders(token, team_id):
    # Get SharePoint site ID for the team
    url = f"https://graph.microsoft.com/v1.0/groups/{team_id}/sites/root"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(url, headers=headers)
    site_id = response.json()["id"]
    
    # Get default document library
    url = f"https://graph.microsoft.com/v1.0/sites/{site_id}/drives"
    response = requests.get(url, headers=headers)
    drive_id = response.json()["value"][0]["id"]
    
    folders = [
        "Active Matters",
        "AI Outputs (pending review)",
        "AI Outputs (approved)",
        "Governance",
        "Templates",
        "Audit Logs"
    ]
    
    for folder in folders:
        url = f"https://graph.microsoft.com/v1.0/drives/{drive_id}/root/children"
        data = {
            "name": folder,
            "folder": {},
            "@microsoft.graph.conflictBehavior": "rename"
        }
        response = requests.post(url, headers=headers, json=data)
        print(f"✓ Folder created: {folder}")

# ═══════════════════════════════════════════════════════════
# STEP 4: CREATE HITL REGISTER (MICROSOFT LIST)
# ═══════════════════════════════════════════════════════════

def create_hitl_register(token, team_id):
    # Get SharePoint site ID
    url = f"https://graph.microsoft.com/v1.0/groups/{team_id}/sites/root"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(url, headers=headers)
    site_id = response.json()["id"]
    
    # Create list
    url = f"https://graph.microsoft.com/v1.0/sites/{site_id}/lists"
    data = {
        "displayName": "HITL Register",
        "columns": [
            {"name": "Task Type", "text": {}},
            {"name": "AI Tool Used", "text": {}},
            {"name": "HITL Reviewer", "text": {}},
            {"name": "Sign-off Date", "dateTime": {}},
            {"name": "Matter Ref", "text": {}}
        ],
        "list": {
            "template": "genericList"
        }
    }
    response = requests.post(url, headers=headers, json=data)
    print("✓ HITL Register created")

# ═══════════════════════════════════════════════════════════
# MAIN EXECUTION
# ═══════════════════════════════════════════════════════════

def main():
    print("\\n" + "="*60)
    print("ASIMOV-AI Environment Provisioning")
    print("="*60 + "\\n")
    
    token = get_access_token()
    team_id = create_team(token)
    
    print("\\nWaiting 30 seconds for team provisioning...")
    import time
    time.sleep(30)
    
    create_channels(token, team_id)
    create_sharepoint_folders(token, team_id)
    create_hitl_register(token, team_id)
    
    print("\\n" + "="*60)
    print("✓ Environment provisioning complete")
    print("="*60)
    print(f"\\nTeam ID: {team_id}")
    print(f"Team Name: {TEAM_NAME}")
    print("\\nNext steps:")
    print("1. Assign HITL reviewers to channels")
    print("2. Configure weekly HITL Register review reminder")
    print("3. Brief team on AI output workflow")
    print("4. Schedule 90-day governance review")

if __name__ == "__main__":
    main()
`;
    
    setGeneratedScript(script);
  };

  const handleNext = () => {
    if (step < questions.length) {
      setStep(step + 1);
    } else {
      generateYAML();
      setStep(step + 1);
    }
  };

  const handleBack = () => {
    if (step > 1) setStep(step - 1);
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
  };

  const sendToClaude = (content, label) => {
    window.sendPrompt(`Here is the ${label}:\n\n\`\`\`\n${content}\n\`\`\``);
  };

  if (step === 8) {
    return (
      <div style={{ padding: '2rem 0' }}>
        <h2 style={{ fontSize: '22px', fontWeight: 500, margin: '0 0 1rem 0' }}>Configuration Complete</h2>
        
        <div style={{ background: 'var(--color-background-secondary)', borderRadius: 'var(--border-radius-lg)', padding: '1rem', marginBottom: '1.5rem' }}>
          <p style={{ fontSize: '14px', color: 'var(--color-text-secondary)', margin: 0 }}>
            Your ASIMOV-AI environment configuration is ready. Choose your deployment method below.
          </p>
        </div>

        <div style={{ marginBottom: '2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 500, margin: 0 }}>Cowork YAML Skill</h3>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button onClick={() => copyToClipboard(generatedYAML)} style={{ fontSize: '13px', padding: '6px 12px' }}>
                Copy
              </button>
              <button onClick={() => sendToClaude(generatedYAML, 'Cowork YAML skill')} style={{ fontSize: '13px', padding: '6px 12px' }}>
                Send to Claude ↗
              </button>
            </div>
          </div>
          <pre style={{ 
            background: 'var(--color-background-primary)', 
            border: '0.5px solid var(--color-border-tertiary)',
            borderRadius: 'var(--border-radius-md)',
            padding: '1rem',
            fontSize: '12px',
            overflow: 'auto',
            maxHeight: '300px',
            margin: 0,
            fontFamily: 'var(--font-mono)'
          }}>
            {generatedYAML}
          </pre>
        </div>

        <div style={{ marginBottom: '2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 500, margin: 0 }}>Microsoft Graph API Script</h3>
            <div style={{ display: 'flex', gap: '8px' }}>
              {!generatedScript && (
                <button onClick={generateMicrosoftGraphScript} style={{ fontSize: '13px', padding: '6px 12px' }}>
                  Generate Script
                </button>
              )}
              {generatedScript && (
                <>
                  <button onClick={() => copyToClipboard(generatedScript)} style={{ fontSize: '13px', padding: '6px 12px' }}>
                    Copy
                  </button>
                  <button onClick={() => sendToClaude(generatedScript, 'Microsoft Graph automation script')} style={{ fontSize: '13px', padding: '6px 12px' }}>
                    Send to Claude ↗
                  </button>
                </>
              )}
            </div>
          </div>
          {generatedScript ? (
            <pre style={{ 
              background: 'var(--color-background-primary)', 
              border: '0.5px solid var(--color-border-tertiary)',
              borderRadius: 'var(--border-radius-md)',
              padding: '1rem',
              fontSize: '12px',
              overflow: 'auto',
              maxHeight: '300px',
              margin: 0,
              fontFamily: 'var(--font-mono)'
            }}>
              {generatedScript}
            </pre>
          ) : (
            <div style={{ 
              background: 'var(--color-background-secondary)', 
              borderRadius: 'var(--border-radius-md)', 
              padding: '1rem',
              fontSize: '13px',
              color: 'var(--color-text-secondary)'
            }}>
              Click "Generate Script" to create a Python automation script using Microsoft Graph API
            </div>
          )}
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
          <button onClick={() => { setStep(1); setGeneratedYAML(''); setGeneratedScript(''); }} style={{ flex: 1 }}>
            Configure Another Environment
          </button>
        </div>
      </div>
    );
  }

  if (step > questions.length) {
    return null;
  }

  return (
    <div style={{ padding: '2rem 0' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', gap: '4px', marginBottom: '1rem' }}>
          {questions.map((_, i) => (
            <div 
              key={i}
              style={{ 
                flex: 1, 
                height: '3px', 
                background: i < step ? 'var(--color-border-info)' : 'var(--color-border-tertiary)',
                borderRadius: '2px'
              }}
            />
          ))}
        </div>
        <p style={{ fontSize: '13px', color: 'var(--color-text-secondary)', margin: 0 }}>
          Question {step} of {questions.length}
        </p>
      </div>

      <h2 style={{ fontSize: '22px', fontWeight: 500, margin: '0 0 1.5rem 0' }}>
        {currentQuestion.question}
      </h2>

      <div style={{ marginBottom: '2rem' }}>
        {currentQuestion.type === 'select' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {currentQuestion.options.map(option => (
              <button
                key={option}
                onClick={() => handleAnswer(option)}
                style={{
                  padding: '12px 16px',
                  textAlign: 'left',
                  background: config[currentQuestion.id] === option ? 'var(--color-background-info)' : 'var(--color-background-primary)',
                  border: config[currentQuestion.id] === option ? '2px solid var(--color-border-info)' : '0.5px solid var(--color-border-tertiary)',
                  borderRadius: 'var(--border-radius-md)',
                  fontSize: '14px',
                  cursor: 'pointer'
                }}
              >
                {option}
              </button>
            ))}
          </div>
        )}

        {currentQuestion.type === 'multiselect' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {currentQuestion.options.map(option => {
              const isSelected = (config[currentQuestion.id] || []).includes(option);
              return (
                <button
                  key={option}
                  onClick={() => handleAnswer(option)}
                  style={{
                    padding: '12px 16px',
                    textAlign: 'left',
                    background: isSelected ? 'var(--color-background-info)' : 'var(--color-background-primary)',
                    border: isSelected ? '2px solid var(--color-border-info)' : '0.5px solid var(--color-border-tertiary)',
                    borderRadius: 'var(--border-radius-md)',
                    fontSize: '14px',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px'
                  }}
                >
                  <div style={{
                    width: '18px',
                    height: '18px',
                    borderRadius: '3px',
                    border: isSelected ? 'none' : '0.5px solid var(--color-border-secondary)',
                    background: isSelected ? 'var(--color-background-info)' : 'transparent',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '12px',
                    color: 'var(--color-text-info)'
                  }}>
                    {isSelected && '✓'}
                  </div>
                  {option}
                </button>
              );
            })}
          </div>
        )}
      </div>

      <div style={{ display: 'flex', gap: '12px' }}>
        {step > 1 && (
          <button onClick={handleBack} style={{ flex: 1 }}>
            Back
          </button>
        )}
        <button 
          onClick={handleNext}
          disabled={!canProceed()}
          style={{ 
            flex: 1,
            opacity: canProceed() ? 1 : 0.5,
            cursor: canProceed() ? 'pointer' : 'not-allowed'
          }}
        >
          {step === questions.length ? 'Generate Configuration' : 'Next'}
        </button>
      </div>
    </div>
  );
}
